version: '3.8'

services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: govwatcher-redis
    env_file:
      - /home/coder/workspace/govwatcher/.env
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: unless-stopped
    networks:
      - govwatcher-network

volumes:
  redis-data:
    driver: local

networks:
  govwatcher-network:
    driver: bridge 